package com.example.theiere.model

class EN {
    val translations = mapOf(
        "USER_NOT_FOUND" to "User not found",
        "ADD_USER" to "Add a new user",
        "CANNOT_LOAD_USER" to "Cannot load user data",
        "MODIF_INFO" to "Edit information",
        "BACK" to "Back",
        "CANCEL" to "Cancel",
        "FIRSTNAME" to "Firstname",
        "LASTNAME" to "Lastname",
        "BEARTHDAY" to "Bearthday",
        "PASSWORD" to "Password",
        "CANCEL_PASSWORD" to "Cancel password modification",
        "EDIT_PASSWORD" to "Edit password",
        "NEW_PASSWORD" to "New password",
        "CONFIRM_PASSWORD" to "Confirm password",
        "USER_UPDATE_FAIL" to "User update failed, please try again later",
        "PASSWORDS_DONT_MATCH" to "Passwords don't match",
        "CANNOT_BE_EMPTY_FIRSTNAME" to "The firstname field cannot be empty",
        "SAVE" to "Save",
        "APP_NAME" to "418 Teapot Application",
        "USERNAME" to "Username",
        "USER_OR_PASSWORD_INCORRECT" to "Incorrect user or password",
        "CONNEXION" to "Sign in",
        "CREATE_USER" to "Create user",
        "UNKNOW" to "Unknown",
        "ERROR_LOADING_TEA" to "Impossible to retrieve teas.",
        "TEA_DATA" to "Tea data",
        "ERROR" to "Error",
        "MUST_FILL" to "Please fill in all required fields (*)",
        "DECONNEXION" to "Sign out",
        "NAME" to "name",
        "TEMPS" to "time",
        "TEMPERATURE" to "temperature",
        "TEA" to "Tea",
        "TEA_NAME" to "Tea name",
        "TEMPERATURE" to "Temperature",
        "ADD_TEA" to "Add tea",
        "TIME" to "Time",
        "FAVORIS" to "favorites",
        "ALL" to "all",
        "DEFAULT" to "default",
        "EDIT" to "edit",
        "ERROR_UPDATE_TEA" to "Failed to update tea data",
        "INVALID_TEA_ID" to "Invalid tea id",
        "TEA_NOT_FOUND" to "Tea not found",
        "ERROR_LOADING_TEA" to "Error loading tea data",
        "UPDATE_TEA" to "Tea setting",
        "UPDATE" to "Update",
        "CONVERTER" to "Converter °C/°F",
        "FILTER_BY_NAME" to "Filter by name",
        "WAITING_TIME" to "Waiting time",
        "TEMP_TO_REACH" to "Temperature to reach",
        "PREPARATION" to "in preparation",
        "TEMP_ACTU" to "Current temperature",
        "MESSAGE_TIMER1" to "If this message is displayed for",
        "MESSAGE_TIMER2" to "too long",
        "MESSAGE_TIMER3" to ", it means that you are not connected to your teapot",
        "TO_CONNECT1" to "In order ",
        "TO_CONNECT2" to "to connect",
        "TO_CONNECT3" to ", activate your ",
        "TEA_READY" to "Tea ready",
        "TEAPOT" to "teapot"

    )
}
