package com.example.theiere.model

class FR {
    val translations = mapOf(
        "USER_NOT_FOUND" to "Utilisateur non trouvé",
        "ADD_USER" to "Ajouter un utilisateur",
        "CANNOT_LOAD_USER" to "Impossible de charger les données de l'utilisateur",
        "MODIF_INFO" to "Modifier les informations",
        "BACK" to "Retour",
        "CANCEL" to "Annuler",
        "FIRSTNAME" to "Prénom",
        "LASTNAME" to "Nom",
        "BEARTHDAY" to "Date de naissance",
        "PASSWORD" to "Mot de passe",
        "CANCEL_PASSWORD" to "Annuler la modification du mot de passe",
        "EDIT_PASSWORD" to "Modifier le mot de passe",
        "NEW_PASSWORD" to "Nouveau mot de passe",
        "CONFIRM_PASSWORD" to "Confirmer le mot de passe",
        "USER_UPDATE_FAIL" to "Échec de la mise à jour de l'utilisateur, veuillez réessayer plus tard",
        "PASSWORDS_DONT_MATCH" to "Les mots de passe ne correspondent pas",
        "CANNOT_BE_EMPTY_FIRSTNAME" to "Le champ prénom ne peut être vide",
        "SAVE" to "Enregistrer",
        "APP_NAME" to "Application Théière 418",
        "USERNAME" to "Nom d'utilisateur",
        "USER_OR_PASSWORD_INCORRECT" to "Utilisateur ou mot de passe incorrect",
        "CONNEXION" to "Se connecter",
        "CREATE_USER" to "Créer un utilisateur",
        "UNKNOW" to "Inconnu",
        "ERROR_LOADING_TEA" to "Impossible de récupérer les thés.",
        "TEA_DATA" to "Données des thés",
        "ERROR" to "Erreur",
        "MUST_FILL" to "Veuillez remplir tous les champs obligatoires (*)",
        "DECONNEXION" to "Déconnexion",
        "NAME" to "nom",
        "TEMPS" to "temps",
        "TEMPERATURE" to "température",
        "TEA" to "Thé",
        "TEA_NAME" to "Nom du thé",
        "TEMPERATURE" to "Température",
        "ADD_TEA" to "Ajouter un thé",
        "TIME" to "Temps",
        "FAVORIS" to "favoris",
        "ALL" to "all",
        "DEFAULT" to "défaut",
        "EDIT" to "modification",
        "ERROR_UPDATE_TEA" to "Erreur dans la mise à jour des données du thé",
        "INVALID_TEA_ID" to "Identifiant du thé invalide.",
        "TEA_NOT_FOUND" to "Thé non trouvé",
        "ERROR_LOADING_TEA" to "Erreur lors de la récupération des données du thé",
        "UPDATE_TEA" to "Modification du thé",
        "UPDATE" to "Mise à jour",
        "CONVERTER" to "Convertisseur °C/°F",
        "FILTER_BY_NAME" to "Rechercher par nom",
        "WAITING_TIME" to "Temps à patienter",
        "TEMP_TO_REACH" to "Température à atteindre",
        "PREPARATION" to "en cours de préparation",
        "TEMP_ACTU" to "Température actuelle",
        "MESSAGE_TIMER1" to "Si ce message s'affiche pendant ",
        "MESSAGE_TIMER2" to "trop longtemps",
        "MESSAGE_TIMER3" to ", cela signifie que vous n'êtes pas connecté à votre théière",
        "TO_CONNECT1" to "Pour vous ",
        "TO_CONNECT2" to "connecter",
        "TO_CONNECT3" to ", activez votre ",
        "TEA_READY" to "Votre thé est prêt",
        "TEAPOT" to "théière"
    )
}
